name: Teste

on:
  workflow_dispatch:

jobs:
  teste:
    runs-on: ubuntu-latest
    environment: PRD
    steps:
      - run: |
          printf %.1s "${{ secrets.A }}"
          echo "${{ vars.B }}"
