name: Teste

on:
  workflow_dispatch:

jobs:
  teste:
    runs-on: ubuntu-latest
    environment: PRD
    steps:
      - run: |
          printf "%.1s\n" "${{ secrets.A }}"
          echo "${{ vars.B }}"
